#!/bin/bash

#set kbd repetition
xset r rate 180 40 

#toggle keyboard layout us/br
LAYOUT=$(setxkbmap -query | grep -oP "us|br") 
if [ $LAYOUT = 'us' ]
then
	setxkbmap -model abnt2 -layout br -variant abnt2
else
	setxkbmap us
fi
